# Busca Cega

Abordagem de busca que não considera nenhuma informação sobre qual sucessor é mais promissor para atingir uma meta (objetivo)
###### Passos
- Formular objetivo
- Formular a busca
- Executar

### Modelando o problema
- Sliding Puzzle
<img src="images/sliding_puzzle.gif" width="250" align="center">

In [29]:
import numpy as np

class SlidingPuzzle():
    def __init__(self, num_blocos):
        '''
        Construtor
        Args:
            - num_blocos: numero de blocos por linha e coluna, valor inteiro (Ex: 3 significa 3 linhas e 3 colunas)
        '''
        self.num_blocos = num_blocos

    def _encontra_posicao(self, estado, elemento):
        '''
        Varre todo o tabuleiro (estado) e verifica em qual posição 'elemento' está
        Args:
            - estado: matriz contendo o estado do tabuleiro
            - elemento: elemento a ser buscado na matriz
        Return:
            - Retorna a linha e coluna onde o elemento se encontra
        '''
        for i in range (self.num_blocos):
            for j in range (self.num_blocos):
                if estado [i,j] == elemento:
                    return i,j
        return None, None

        
    def verifica_estados(self, atual, objetivo):
        '''
        Verifica se dois estados são iguais
        Args:
            - atual: matriz que descreve o estado atual
            - objetivo: matriz que descreve o estado objetivo
        Return:
            - booleano dizendo se o estado atual é ou não o objetivo
        '''
        for i in range (self.num_blocos):
            for j in range (self.num_blocos):
                if atual [i,j] != objetivo [i,j]:
                    return False
        return True

    def expande_estados(self, atual):
        '''
        Dado o estado atual, realiza a expansão de estados
        Args:
            - atual: matriz que descreve o estado atual
        Return:
            - lista com os novos estados após a expansão
        '''
        novos_estados = []
        linha, coluna = self._encontra_posicao(atual,0)
        
        # CIMA
        if linha > 0:
            novo_estado = np.copy(atual)
            nova_linha = linha - 1
            
            bloco_alvo = novo_estado[nova_linha, coluna]
            novo_estado[nova_linha, coluna] = 0
            novo_estado[linha, coluna] = bloco_alvo
            
            novos_estados.append(novo_estado)
            
        # BAIXO
        if linha < self.num_blocos - 1:
            novo_estado = np.copy(atual)
            nova_linha = linha + 1
            
            bloco_alvo = novo_estado[nova_linha, coluna]
            novo_estado[nova_linha, coluna] = 0
            novo_estado[linha, coluna] = bloco_alvo
            
            novos_estados.append(novo_estado)
            
        # ESQUERDA
        if coluna > 0:
            novo_estado = np.copy(atual)
            nova_coluna = coluna - 1
            
            bloco_alvo = novo_estado[linha, nova_coluna]
            novo_estado[linha, nova_coluna] = 0
            novo_estado[linha, coluna] = bloco_alvo
            
            novos_estados.append(novo_estado)
            
        # DIREITA
        if coluna < self.num_blocos -1:
            novo_estado = np.copy(atual)
            nova_linha = coluna + 1
            
            bloco_alvo = novo_estado[linha, nova_coluna]
            novo_estado[linha, nova_coluna] = 0
            novo_estado[linha, coluna] = bloco_alvo
            
            novos_estados.append(novo_estado)
        
        return novos_estados
        
    

### Formulando Busca

#### Busca em largura (BrFS– Breadth-first search)

Realiza a busca em nível. Imagine uma árvore de estados, nela a busca é realizada sequencialmente em cada nó do mesmo nível

<img src="images/bfs.gif" width="250" align="center">

In [34]:
from queue import Queue

class BreadthFirstSearch():
    def __init__(self, problema):
        '''
        Construtor
        Args:
            - problema: objeto do problema a ser solucionado
        '''
        self.problema = problema
        
    def _verifica_visitado(self, estado, estados_visitados):
        '''
        Verifica se 'estado' está na lista de estados visitados
        Args:
            - estado: estado qualquer do tabuleiro
            - estados_visitados: lista com todos os estados já visitados
        Return:
            - booleano dizendo se o estado foi visitado ou não
        '''
        for i in estados_visitados:
            if self.problema.verifica_estados(i,estado):
                return True
        return False

    
    def busca(self, inicio, fim):
        '''
        Realiza a busca BFS, armazenando os estados em uma FILA
        Args:
            - inicio: estado inicial do problema
            - fim: estado objetivo
        Return:
            - booleano se a solução foi encontrada, lista dos estados visitados, quantidade de estados visitados
        '''
        fila = Queue()
        fila.put(inicio)
        
        solucao_encontrada = False
        estados_visitados = []
        cont_estados = 0
        
        while not fila.empty():
            atual = fila.get()
            estados_visitados.append(atual)
            
            if self.problema.verifica_estados(atual, fim):
                solucao_encontrada = True
                break
            else:
                cont_estados += 1            
                print(f"visitando #{cont_estados}")
                novos_estados = self.problema.expande_estados(atual)
                for i in novos_estados:
                      if not self._verifica_visitado(i, estados_visitados):
                          print(i)
                          fila.put(i)
                            
        return solucao_encontrada, estados_visitados, cont_estados
      

#### Busca em profundidade (DFS – Depth-first search)

Realiza a busca por ramo. Imagine uma árvore de estados, nela a busca é realizada sequencialmente em cada ramo, e só após completá-lo, busca no ramo vizinho.

<img src="images/dfs.gif" width="250" align="center">

In [35]:
from queue import LifoQueue

class DepthFirstSearch():
    def __init__(self, problema):
        '''
        Construtor
        Args:
            - problema: objeto do problema a ser solucionado
        '''
        self.problema = problema
        
    def _verifica_visitado(self, estado, estados_visitados):
        '''
        Verifica se 'estado' está na lista de estados visitados
        Args:
            - estado: estado qualquer do tabuleiro
            - estados_visitados: lista com todos os estados já visitados
        Return:
            - booleano dizendo se o estado foi visitado ou não
        '''
        for i in estados_visitados:
            if self.problema.verifica_estados(i,estado):
                return True
        return False
    
    def busca(self, inicio, fim):
        '''
        Realiza a busca DFS, armazenando os estados em uma PILHA
        Args:
            - inicio: estado inicial do problema
            - fim: estado objetivo
        Return:
            - booleano se a solução foi encontrada, lista dos estados visitados, quantidade de estados visitados
        '''
        pilha = LifoQueue()
        pilha.put(inicio)
        
        solucao_encontrada = False
        estados_visitados = []
        cont_estados = 0
        
        while not pilha.empty():
            atual = pilha.get()
            estados_visitados.append(atual)
            
            if self.problema.verifica_estados(atual, fim):
                solucao_encontrada = True
                break
            else:
                cont_estados += 1            
                print(f"visitando #{cont_estados}")
                novos_estados = self.problema.expande_estados(atual)
                for i in novos_estados:
                      if not self._verifica_visitado(i, estados_visitados):
                          print(i)
                          pilha.put(i)
                            
        return solucao_encontrada, estados_visitados, cont_estados


### Executando

In [36]:
# Criando objeto do problema
problema = SlidingPuzzle(3)

# Criando Matriz inicial e matriz alvo
start = np.matrix([[1,0,2],[8,4,3],[7,6,5]])
target = np.matrix([[1,2,3],[8,0,4],[7,6,5]])

# Mostrando informações iniciais
print(f"Initial state: \n{start}")
print("*"*15)
print(f"Target state: \n{target}")
print("*"*15)

Initial state: 
[[1 0 2]
 [8 4 3]
 [7 6 5]]
***************
Target state: 
[[1 2 3]
 [8 0 4]
 [7 6 5]]
***************


In [38]:
# Execução do BFS
bfs = BreadthFirstSearch(problema)

bfs_solucao, bfs_estados_visitados, bfs_num_visitados = bfs.busca(start, target) # chamando busca

if bfs_solucao:
    print(f"Solution found!!!")
else:
    print("Solution not found!!!")

visitando #1
[[1 4 2]
 [8 0 3]
 [7 6 5]]
[[0 1 2]
 [8 4 3]
 [7 6 5]]
[[0 1 2]
 [8 4 3]
 [7 6 5]]
visitando #2
[[1 4 2]
 [8 6 3]
 [7 0 5]]
[[1 4 2]
 [0 8 3]
 [7 6 5]]
[[1 4 2]
 [0 8 3]
 [7 6 5]]
visitando #3


UnboundLocalError: cannot access local variable 'nova_coluna' where it is not associated with a value

In [39]:
# Execução do DFS
dfs = DepthFirstSearch(problema)

dfs_solucao, dfs_estados_visitados, dfs_num_visitados = dfs.busca(start, target) # chamando busca

if dfs_solucao:
    print(f"Solution found!!!")
else:
    print("Solution not found!!!")

visitando #1
[[1 4 2]
 [8 0 3]
 [7 6 5]]
[[0 1 2]
 [8 4 3]
 [7 6 5]]
[[0 1 2]
 [8 4 3]
 [7 6 5]]
visitando #2


UnboundLocalError: cannot access local variable 'nova_coluna' where it is not associated with a value

In [40]:
# Apresentando resultados
print("==== BFS ====")
print(f"Solução encontrada? {bfs_solucao}")
print(f"Número de estados visitados: {bfs_num_visitados}")

print("==== DFS ====")
print(f"Solução encontrada? {dfs_solucao}")
print(f"Número de estados visitados: {dfs_num_visitados}")

==== BFS ====


NameError: name 'bfs_solucao' is not defined